# docker-compose up --scale worker=4
version: '3'

services:
  master:
    image: locustio/locust
    network_mode: host
    volumes:
      - ./src:/mnt/locust
      - $HOME/sinan_locust_log:/mnt/locust_log
      - ${TRACEFILE}:/mnt/rps.txt
    command: --headless -f /mnt/locust/hotel_rps_1.py -H http://127.0.0.1:30001
             --logfile /mnt/locust_log/hotel_locust_log.txt
             --csv=/mnt/locust_log/hotel --csv-full-history --master
  
  worker:
    image: locustio/locust
    volumes:
      - ./src:/mnt/locust
      - $HOME/sinan_locust_log:/mnt/locust_log
      - ${TRACEFILE}:/mnt/rps.txt
    network_mode: "host"
    command: -f /mnt/locust/hotel_rps_1.py --worker